class GenomeDB(object):
    """To be a central controller of directory of JBrowse data with accessors
    for tracks, seqs, etc. Currently only defines a single method, though.
    """
    def precompression_htaccess(self, *extensions):
        """Returns a string to write into a .htaccess file that will instruct
        Apache (if AllowOverride is on) to set the proper "Content-Encoding
        gzip" headers on precompressed files (.jsonz and .txtz).
        """
        regex = '({})$'.format('|'.join(extensions))
        regex = regex.replace('.', '\.')
        package = self.__class__.__name__
        return """# This Apache .htaccess file is generated by JBrowse ({package}) for
# serving precompressed files ({extensions}) with the proper
# Content-Encoding HTTP headers.  In order for Apache to pay attention
# to this, its AllowOverride configuration directive for this
# filesystem location must allow FileInfo overrides.
<IfModule mod_gzip.c>
    mod_gzip_item_exclude "{regex}"
</IfModule>
<IfModule setenvif.c>
    SetEnvIf Request_URI "{regex}" no-gzip dont-vary
</IfModule>
<IfModule mod_headers.c>
  <FilesMatch "{regex}">
    Header onsuccess set Content-Encoding gzip
  </FilesMatch>
</IfModule>
""".format(package=package, extensions=' '.join(extensions), regex=regex)
